global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'asset_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['asset-service:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

rule_files: []
